# Generated by Django 2.1.5 on 2019-02-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('name', models.TextField()),
                ('cal', models.IntegerField()),
                ('materials', models.TextField()),
            ],
        ),
    ]
