# Generated by Django 2.1.5 on 2019-01-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kr', models.TextField()),
                ('title_en', models.TextField()),
                ('sectators', models.IntegerField()),
                ('summary', models.TextField()),
                ('info_url', models.TextField()),
                ('score', models.FloatField()),
                ('poster', models.ImageField(blank=True, upload_to=models.TextField())),
                ('picture1', models.ImageField(blank=True, upload_to=models.TextField())),
                ('picture2', models.ImageField(blank=True, upload_to=models.TextField())),
                ('picture3', models.ImageField(blank=True, upload_to=models.TextField())),
            ],
        ),
    ]
