# Generated by Django 2.1.5 on 2019-01-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='sectators',
            new_name='spectators',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
